-- 028_agent_lineage.sql
-- Adds Claude Code subagent lineage tracking (v2.1.139 + v2.1.145).
--
-- Claude Code now carries `x-claude-code-agent-id` / `x-claude-code-parent-agent-id`
-- HTTP headers on every API request and exposes the same as `agent_id` /
-- `parent_agent_id` attributes on `claude_code.tool` and
-- `claude_code.llm_request` OTEL spans. We persist them per knowledge row so
-- recall can answer "what did subagent X (dispatched from parent Y) produce".
--
-- Both columns are nullable — pre-existing rows and callers that don't pass
-- the ids stay unaffected.
--
-- The columns themselves are added by `base_schema.apply_core_column_migrations`,
-- which runs before this file and is PRAGMA-guarded. This migration used to
-- ALTER them in too, which meant it raised `duplicate column name: agent_id`
-- on every startup and was never recorded as applied - it had still not applied
-- on a database that had been running it for months.
--
-- The two partial indexes this migration used to create are also now issued
-- unconditionally by `apply_core_column_migrations`, so nothing is left for
-- this file to do - it stays as a historical marker so `version` 028 remains
-- a recorded, applied row in every database, rather than a gap in the chain.
