-- 900_reflection_phase_errors.sql
-- Make failing reflection phases visible.
--
-- run_full() runs six phases and each one catches its own exceptions, returning
-- {"error": "..."} instead of raising. _save_report then persisted only digest
-- and synthesis counters, so every one of those errors was dropped on the floor
-- and survived only in stderr. That is how `fact_merge` stayed broken for
-- months with "table knowledge has no column named updated_at": nothing the
-- report kept ever mentioned it.
--
-- One JSON blob of {phase: message} per report, so a failing phase is queryable
-- instead of archaeological.
--
-- This file is a comment-only marker: `ALTER TABLE ADD COLUMN` is not safe
-- to repeat (SQLite has no `ADD COLUMN IF NOT EXISTS`, and the
-- `MigrationRunner` that runs versions >= TRANSACTIONAL_SCHEMA_VERSION has
-- no tolerance for "duplicate column name"), so the real DDL lives in
-- `base_schema.apply_reflection_report_column_migrations`, PRAGMA-guarded
-- so it is safe to replay, called from `Store._apply_sql_migrations` after
-- this loop has ensured `reflection_reports` exists. This file stays on
-- disk so version 900 remains a recorded tracker row (mirrors
-- 028_agent_lineage.sql).
