from __future__ import annotations

import re

MAX_LEXICAL_TERMS = 32
QUESTION_STOPWORDS = frozenset(
    [
        "a",
        "an",
        "the",
        "what",
        "which",
        "who",
        "whom",
        "whose",
        "how",
        "when",
        "where",
        "why",
        "is",
        "are",
        "was",
        "were",
        "be",
        "been",
        "being",
        "do",
        "does",
        "did",
        "have",
        "has",
        "had",
        "to",
        "of",
        "in",
        "on",
        "at",
        "for",
        "with",
        "and",
        "or",
        "as",
        "by",
        "about",
        "can",
        "could",
        "would",
        "should",
        "will",
        "please",
        "tell",
        "me",
        "know",
        "remember",
        "что",
        "какой",
        "какая",
        "какие",
        "какое",
        "кто",
        "кого",
        "кому",
        "чей",
        "чья",
        "чьи",
        "как",
        "когда",
        "где",
        "куда",
        "почему",
        "зачем",
        "это",
        "есть",
        "был",
        "была",
        "были",
        "быть",
        "в",
        "во",
        "на",
        "для",
        "от",
        "до",
        "по",
        "из",
        "у",
        "и",
        "или",
        "а",
        "о",
        "об",
        "про",
        "с",
        "со",
        "мне",
        "меня",
        "ты",
        "вы",
        "пожалуйста",
        "расскажи",
        "напомни",
    ]
)
_TERM = re.compile(r"\w+(?:[./:-]\w+)*", re.UNICODE)


def lexical_terms(query: str) -> list[str]:
    terms = list(dict.fromkeys(_TERM.findall(query.casefold())))
    meaningful = [term for term in terms if term not in QUESTION_STOPWORDS]
    return (meaningful or terms)[:MAX_LEXICAL_TERMS]
